development:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: facilito_development
  pool: 5
  username: postgres
  password: bat86

test:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: facilito_test
  pool: 5
  username: postgres
  password: bat86

production:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: facilito_production
  pool: 5
  username: 
  password: 
